version: '3.8'

services:
  tag-onboarding:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      MONGO_URI: mongodb://root:password@mongo:27017
      MONGO_COLLECTION: user
  
  mongo:
    image: mongo:3.6.17-xenial
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: user
